--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NathaLMV/SurrealFFA
build-by-default: true
branches:
- main
projects:
  SurrealFFA:
    path: ""
    entry: src
    icon: icon.png
...
